name: ChaveamentoInsetos
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.11
  page_transition: ^1.1.7+6
  cupertino_icons: ^0.1.3
  auto_size_text: ^2.1.0
  flutter_svg: ^0.20.0-nullsafety.3
  flare_splash_screen: ^2.0.1+2
  curved_navigation_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/textos/
    - assets/images/
    - assets/splash.flr

  fonts:
    - family: Open_Sans
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: fonts/Open_Sans/OpenSans-Italic.ttf
          weight: 700

