class Matriz_Ordem_Hexapoda {
  String matrizij;
  String matrizik;
  String imgij;
  String imgik;
  int indiceij;
  int indiceik;

  int i = 0;
  int j = 0;
  int k = 1;

  var matrizindice = ["[0][0]"];
  var matriztexto = ["Asas ausentes ou reduzidas, não funcionais (Figs 9.1-5, 10.1, 13.1, 4-5, 26.105-106, 27.58, 62)"];
  var matrizimg = ["assets/imgchave/1.png"];

  void define() {
    matrizindice.add("[1][0]");
    matrizindice.add("[2][0]");
    matrizindice.add("[1][1]");
    matrizindice.add("[2][2]");
    matrizindice.add("[3][4]");
    matrizindice.add("[4][8]");
    matrizindice.add("[3][5]");
    matrizindice.add("[4][10]");
    matrizindice.add("[5][20]");
    matrizindice.add("[4][11]");
    matrizindice.add("[5][22]");
    matrizindice.add("[2][3]");
    matrizindice.add("[3][6]");
    matrizindice.add("[4][12]");
    matrizindice.add("[5][24]");
    matrizindice.add("[4][13]");
    matrizindice.add("[5][26]");
    matrizindice.add("[3][7]");
    matrizindice.add("[4][14]");
    matrizindice.add("[5][28]");
    matrizindice.add("[4][15]");
    matrizindice.add("[5][30]");
    matrizindice.add("[6][60]");
    matrizindice.add("[7][120]");
    matrizindice.add("[8][240]");
    matrizindice.add("[6][61]");
    matrizindice.add("[7][122]");
    matrizindice.add("[8][244]");
    matrizindice.add("[7][123]");
    matrizindice.add("[8][246]");
    matrizindice.add("[9][492]");
    matrizindice.add("[10][984]");
    matrizindice.add("[9][493]");
    matrizindice.add("[10][986]");
    matrizindice.add("[8][247]");
    matrizindice.add("[9][494]");
    matrizindice.add("[10][988]");
    matrizindice.add("[9][495]");
    matrizindice.add("[10][990]");
    matrizindice.add("[5][31]");
    matrizindice.add("[6][62]");
    matrizindice.add("[7][124]");
    matrizindice.add("[8][248]");
    matrizindice.add("[7][125]");
    matrizindice.add("[8][250]");
    matrizindice.add("[6][63]");
    matrizindice.add("[7][126]");
    matrizindice.add("[8][252]");
    matrizindice.add("[7][127]");
    matrizindice.add("[8][256]");
    matrizindice.add("[9][512]");
    matrizindice.add("[8][257]");
    matrizindice.add("[9][514]");
    matrizindice.add("[0][1]");
    matrizindice.add("[1][2]");
    matrizindice.add("[2][4]");
    matrizindice.add("[3][8]");
    matrizindice.add("[4][16]");
    matrizindice.add("[3][9]");
    matrizindice.add("[4][18]");
    matrizindice.add("[5][36]");
    matrizindice.add("[6][72]");
    matrizindice.add("[5][37]");
    matrizindice.add("[6][74]");
    matrizindice.add("[4][19]");
    matrizindice.add("[5][38]");
    matrizindice.add("[6][76]");
    matrizindice.add("[5][39]");
    matrizindice.add("[6][78]");
    matrizindice.add("[2][5]");
    matrizindice.add("[3][10]");
    matrizindice.add("[4][20]");
    matrizindice.add("[5][40]");
    matrizindice.add("[4][21]");
    matrizindice.add("[5][42]");
    matrizindice.add("[3][11]");
    matrizindice.add("[4][22]");
    matrizindice.add("[5][44]");
    matrizindice.add("[6][88]");
    matrizindice.add("[7][176]");
    matrizindice.add("[6][89]");
    matrizindice.add("[7][178]");
    matrizindice.add("[5][45]");
    matrizindice.add("[6][90]");
    matrizindice.add("[7][180]");
    matrizindice.add("[6][91]");
    matrizindice.add("[7][182]");
    matrizindice.add("[8][364]");
    matrizindice.add("[9][728]");
    matrizindice.add("[8][365]");
    matrizindice.add("[9][730]");
    matrizindice.add("[7][183]");
    matrizindice.add("[8][366]");
    matrizindice.add("[9][732]");
    matrizindice.add("[8][367]");
    matrizindice.add("[9][734]");
    matrizindice.add("[4][23]");
    matrizindice.add("[5][46]");
    matrizindice.add("[6][92]");
    matrizindice.add("[7][184]");
    matrizindice.add("[6][93]");
    matrizindice.add("[7][186]");
    matrizindice.add("[5][47]");
    matrizindice.add("[6][94]");
    matrizindice.add("[7][188]");
    matrizindice.add("[6][95]");
    matrizindice.add("[7][190]");
    matrizindice.add("[8][380]");
    matrizindice.add("[7][191]");
    matrizindice.add("[8][382]");
    matrizindice.add("[9][764]");
    matrizindice.add("[8][383]");
    matrizindice.add("[9][766]");
    matrizindice.add("[1][3]");
    matrizindice.add("[2][6]");
    matrizindice.add("[3][12]");
    matrizindice.add("[4][24]");
    matrizindice.add("[3][13]");
    matrizindice.add("[4][26]");
    matrizindice.add("[2][7]");
    matrizindice.add("[3][14]");
    matrizindice.add("[4][28]");
    matrizindice.add("[3][15]");
    matrizindice.add("[4][30]");
    matrizindice.add("[5][60]");
    matrizindice.add("[6][120]");
    matrizindice.add("[5][61]");
    matrizindice.add("[6][122]");
    matrizindice.add("[4][31]");
    matrizindice.add("[5][62]");
    matrizindice.add("[6][124]");
    matrizindice.add("[5][63]");
    matrizindice.add("[6][126]");

    //Inicio dos textos da matriz
//1
    matriztexto.add("Inseto séssil ou de pouca mobilidade encontrado em plantas; corpo achatado ou arredondado, com ou sem carapaça ou cobertura de cera; aparelho bucal sugador; pernas presentes, ausentes ou reduzidas; se presentes, com tarsos monômeros e garras simples (Figs 25.6-23) (fêmeas de cochonilhas)");
    matriztexto.add("Hemiptera");
    matriztexto.add("Inseto não séssil, sem carapaça ou cobertura de cera; aparelho bucal variável; pernas presentes e funcionais");
    matriztexto.add("Aparelho bucal do tipo entognato, oculto e alojado em uma cavidade da cápsula cefálica (Figs 9.1-5, 10.1, 11.1); olhos rudimentares ou ausentes; tarsos com apenas um segmento");
    matriztexto.add("Antenas ausentes; perna anterior alongada e com muitas cerdas longas; abdômen com 12 segmentos; comprimento do corpo 0,5-2 mm (Fig. 10.1)");
    matriztexto.add("Protura");
    matriztexto.add("Antenas presentes; perna anterior não modificada; abdômen com 10 segmentos ou menos");
    matriztexto.add("Cercos presentes, longos e segmentados ou em forma de pinça; corpo estreito e alongado, abdômen com 10 segmentos, colóforo, fúrcula e retináculo ausentes; comprimento do corpo 1-58 mm (Figs 11.21-24)");
    matriztexto.add("Diplura");
    matriztexto.add("Cercos ausentes; corpo curto; abdômen com, no máximo, 6 segmentos; colóforo, fúrcula e retináculo presentes; comprimento do corpo 0,25-6 mm");
    matriztexto.add("Collembola");
    matriztexto.add("Aparelho bucal do tipo ectognato, não alojado em uma cavidade da cabeça; olhos presentes ou ausentes; tarsos geralmente com mais de 2 segmentos");
    matriztexto.add("Três filamentos caudais presentes (cercos e paracerco); abdômen com estilos ventrais (Figs 12.1, 13.1-2)");
    matriztexto.add("Olhos compostos grandes, geralmente contíguos; tórax arqueado; comprimento do corpo 6-20 mm (Fig. 12.1) ");
    matriztexto.add("Archaeognatha");
    matriztexto.add("Olhos compostos pequenos ou ausentes; corpo achatado dorso-ventralmente; comprimento do corpo 2-15 mm (Figs 13.1, 4-5)");
    matriztexto.add("Zygentoma");
    matriztexto.add("Cercos presentes ou ausentes; paracerco ausente; abdômen sem estilos ventrais");
    matriztexto.add("Abdômen com constrição conspícua na base, formando uma cintura; tarsos pentâmeros; aparelho bucal mastigador; antena geniculada ou filiforme (formigas e vespas ápteras) (Figs 27.58, 27.62)");
    matriztexto.add("Hymenoptera");
    matriztexto.add("Abdômen sem constrição na base; tarsos, aparelho bucal e antenas variáveis");
    matriztexto.add("Cercos presentes; aparelho bucal mastigador; antenas longas, filiformes ou moniliformes (ortopteroides) (Figs 16.4, 19.76, 20.7, 21.32, 23.15, 23.19-24)");
    matriztexto.add("Tarsos pentâmeros");
    matriztexto.add("Corpo achatado dorso-ventralmente; pronoto cobrindo boa parte da cabeça em vista dorsal; tarsos pentâmeros; comprimento 5-90 mm (baratas ápteras) (Figs 23.1-6)");
    matriztexto.add("Blattaria");
    matriztexto.add("Tarsos com 2-4 segmentos");
    matriztexto.add("Perna posterior saltadora, com o fêmur dilatado; pronoto dobrado lateralmente, cobrindo a região pleural; tarsos com 3-4 segmentos; comprimento do corpo 5-150 mm (Figs 19.11,19.76)");
    matriztexto.add("Orthoptera");
    matriztexto.add("Perna posterior não saltadora; pronoto não dobrado lateral- mente");
    matriztexto.add("Tarsos trímeros; olho composto bem desenvolvido");
    matriztexto.add("Cercos grandes, não segmentados, em forma de pinça (Fig. 17.10); comprimento 3-35 mm");
    matriztexto.add("Dermaptera");
    matriztexto.add("Cercos com dois segmentos, não em forma de pinça; basitarso anterior muito dilatado; comprimento 4-30 mm (Fig. 20.7)");
    matriztexto.add("Embioptera");
    matriztexto.add("Tarsos dímeros ou tetrâmeros; olho composto ausente ou vestigial");
    matriztexto.add("Tarsos dímeros; cercos com apenas um segmento; antena com nove artículos; comprimento 2-4 mm (Fig. 16.4)");
    matriztexto.add("Zoraptera");
    matriztexto.add("Tarsos tetrâmeros; cercos dímeros; antena com 10-21 artículos; comprimento 3-20 mm (operários e soldados de cupins) (Figs 23.22-24)");
    matriztexto.add("Blattaria");
    matriztexto.add("Cercos ausentes; aparelho bucal e antenas variáveis");
    matriztexto.add("Tarsos pentâmeros; aparelho bucal sugador; antenas curtas");
    matriztexto.add("Corpo achatado lateralmente; pernas longas, saltadoras (Fig. 35.1)");
    matriztexto.add("Siphonaptera");
    matriztexto.add("Corpo achatado dorso-ventralmente; pernas curtas (Fig. 36.73)");
    matriztexto.add("Diptera");
    matriztexto.add("Tarsos com 1-3 segmentos; aparelho bucal e antenas variáveis");
    matriztexto.add("Aparelho bucal sugador formando um rostro alongado e segmentado (Figs 25.1, 3)");
    matriztexto.add("Hemiptera");
    matriztexto.add("Aparelho bucal variável, nunca formando um rostro longo e segmentado");
    matriztexto.add("Pernas terminando no arólio, que forma uma vesícula eversível; garras reduzidas; aparelho bucal sugador cônico, curto e não segmentado (Fig. 24.26) (tripes ápteros)");
    matriztexto.add("Thysanoptera");
    matriztexto.add("Pernas terminando em garras bem desenvolvidas; aparelho bucal variável (Figs 26.7, 26.64-103)");
    matriztexto.add("Psocodea");
    matriztexto.add("Asas presentes e funcionais (Figs 14.1, 4, 17.21, 18.3, 24.1, 32.1)");
    matriztexto.add("Com um ou dois pares de asas de textura uniforme, não engrossadas nem endurecidas (mas podem estar cobertas de pelos ou escamas, e apresentar pigmentação)");
    matriztexto.add("Com apenas um par de asas");
    matriztexto.add("Asas posteriores em forma de halteres (Fig. 36.6); tarsos pentâmeros; aparelho bucal sugador (atrofiado em algumas espécies)");
    matriztexto.add("Diptera");
    matriztexto.add("Asas posteriores não em forma de halteres; tarsos com 1-5 segmentos; aparelho bucal variável");
    matriztexto.add("Cercos presentes");
    matriztexto.add("Pernas posteriores saltadoras; aparelho bucal mastigador; antena mais longa que a cabeça, cercos curtos; tarsos com 2-3 segmentos (Figs 19.1, 63)");
    matriztexto.add("Orthoptera");
    matriztexto.add("Pernas posteriores não saltadoras; aparelho bucal atrofiado; antena muito curta, em forma de cerda; cercos longos; tarsos com 4-5 segmentos (Figs 14.61-66) ");
    matriztexto.add("Ephemeroptera");
    matriztexto.add("Cercos ausentes");
    matriztexto.add("Asa anterior em forma de halteres; asa posterior bem desenvolvida; antena flabelada (Figs 30.1-3)");
    matriztexto.add("Strepsiptera");
    matriztexto.add("Asa anterior bem desenvolvida; asa posterior vestigial; antena filiforme; aparelho bucal atrofiado; tarsos com um segmento (macho de cochonilha)");
    matriztexto.add("Hemiptera");
    matriztexto.add("Com dois pares de asas");
    matriztexto.add("Asas cobertas de escamas ou pelos, pelo menos parcialmente; aparelho bucal em forma de uma probóscide enrolada (Fig. 33.1) ou atrofiado (Fig. 32.1); antenas longas");
    matriztexto.add("Asas cobertas de escamas; aparelho bucal em forma de uma probóscide enrolada (Fig. 33.1), raramente atrofiado");
    matriztexto.add("Lepidoptera");
    matriztexto.add("Asas cobertas de pelos; aparelho bucal atrofiado (Fig. 32.1)");
    matriztexto.add("Trichoptera");
    matriztexto.add("Asas não cobertas por escamas nem pelos; aparelho bucal mastigador, sugador ou atrofiado, nunca em forma de uma probóscide enrolada; antenas curtas ou longas ");
    matriztexto.add("Tarsos com 1-3 segmentos");
    matriztexto.add("Aparelho bucal sugador em forma de uma probóscide longa e segmentada ou cônica; cercos ausentes");
    matriztexto.add("Aparelho bucal longo e segmentado; garras bem desenvolvidas; asas não franjadas (Figs 25.1-2, 25.30-31) ");
    matriztexto.add("Hemiptera");
    matriztexto.add("Aparelho bucal curto e cônico; garras reduzidas; pernas terminando no arólio, que forma uma vesícula eversível (tripes alados) (Fig. 24.1)");
    matriztexto.add("Thysanoptera");
    matriztexto.add("Aparelho bucal mandibulado ou atrofiado; cercos ausentes ou presentes");
    matriztexto.add("Antenas curtas, em forma de cerda; olhos grandes e salientes; abdômen longo e fino (Figs 15.1-2)");
    matriztexto.add("Odonata");
    matriztexto.add("Antenas longas, filiformes ou moniliformes; olhos e abdômen variáveis");
    matriztexto.add("Cercos segmentados; antenas longas");
    matriztexto.add("Cercos dímeros; basitarso anterior muito dilatado; antenas moniliformes (Fig. 20.8)");
    matriztexto.add("Embioptera");
    matriztexto.add("Cercos longos, com muitos segmentos; basitarso anterior não dilatado; antenas filiformes (Figs 18.3)");
    matriztexto.add("Plecoptera");
    matriztexto.add("Cercos não segmentados ou ausentes");
    matriztexto.add("Cercos ausentes; clípeo inflado; antena filiforme; tarso com 2-3 segmentos (Figs 26.1-6)");
    matriztexto.add("Psocodea");
    matriztexto.add("Cercos presentes; antena moniliforme; tarsos dímeros (Fig. 16.5)");
    matriztexto.add("Zoraptera");
    matriztexto.add("Tarsos com 4-5 segmentos");
    matriztexto.add("Cercos segmentados");
    matriztexto.add("Antena curta, em forma de cerda; asa posterior muito menor que a anterior; aparelho bucal atrofiado (Fig. 14.4)");
    matriztexto.add("Ephemeroptera");
    matriztexto.add("Antena longa, moniliforme ou filiforme; asas de tamanho e forma semelhantes; aparelho bucal mandibulado funcional (cupins alados) (Figs 23.19-20)");
    matriztexto.add("Blattaria");
    matriztexto.add("Cercos não segmentados ou ausentes");
    matriztexto.add("Asa posterior muito menor que a anterior; asa anterior com menos de 20 células; abdômen geralmente com um estreitamento, formando um “cintura” ");
    matriztexto.add("Hymenoptera");
    matriztexto.add("Asas anterior e posterior aproximadamente do mesmo tamanho e formato; asa anterior com mais de 20 células; abdômen sem estreitamento");
    matriztexto.add("Cabeça alongada, formando um rostro; região costal da asa anterior sem veias transversais; comprimento do corpo 14-24 mm (Fig. 34.1)");
    matriztexto.add("Mecoptera");
    matriztexto.add("Cabeça não alongada; região costal da asa anterior geralmente com muitas veias transversais");
    matriztexto.add("Região basal da asa posterior mais larga na base que na asa anterior (Figs 28.4-8)");
    matriztexto.add("Megaloptera");
    matriztexto.add("Região basal da asa posterior semelhante ou mais estreita que na asa anterior (Figs 29.2-8)");
    matriztexto.add("Neuroptera");
    matriztexto.add("Asa anterior engrossada ou endurecida, pelo menos na região proximal; asa posterior membranosa, claramente mais fina que a anterior; quando em repouso, asa anterior cobre a asa posterior e pelo menos parte do abdômen");
    matriztexto.add("Asa anterior sem veias; asa posterior geralmente permanece dobrada e oculta sob a anterior quando em repouso; aparelho bucal mastigador");
    matriztexto.add("Cercos grandes, em forma de pinça; asa anterior curta, cobrindo pequena parte do abdômen (Figs 17.20-21)");
    matriztexto.add("Dermaptera");
    matriztexto.add("Cercos ausentes; asa anterior (élitro) de tamanho variável (Figs 31.2, 31.141-156, 31.589-632)");
    matriztexto.add("Coleoptera");
    matriztexto.add("Asa anterior com veias; aparelho bucal mastigador ou sugador");
    matriztexto.add("Aparelho bucal sugador em forma de rostro segmentado; cercos ausentes (Heteroptera) (Figs 28.104-255) ");
    matriztexto.add("Hemiptera");
    matriztexto.add("Aparelho bucal mastigador; cercos presentes");
    matriztexto.add("Coxas grandes, de formato aproximadamente triangular, mais longas que um terço do comprimento do fêmur; tarsos pentâmeros; cercos  segmentados");
    matriztexto.add("Corpo largo e achatado; cabeça pelo menos parcialmente coberta pelo pronoto; perna anterior semelhante às outras; protórax curto (baratas) (Figs 23.1-15)");
    matriztexto.add("Blattaria");
    matriztexto.add("Corpo estreito e não achatado; cabeça não coberta pelo pronoto; perna anterior raptorial, com espinhos grandes; protórax alongado (Figs 22.1-6)");
    matriztexto.add("Mantodea");
    matriztexto.add("Coxas pequenas, muito mais curtas que o fêmur; tarsos com 2-5 segmentos; cercos segmentados ou simples");
    matriztexto.add("Perna posterior saltadora; com fêmur muito mais largo que a tíbia; cercos com 2-4 segmentos; pronoto grande, cobrindo parte da região lateral do tórax (Figs 19.1, 19.13, 19.19, 19.44-60)");
    matriztexto.add("Orthoptera");
    matriztexto.add("Perna posterior semelhantes às outras; cercos pentâmeros; pronoto pequeno; corpo alongado, em forma de graveto (bicho-pau) (Figs 21.54-55)");
    matriztexto.add("Phasmatodea");


    matrizimg.add("assets/imgchave/2.png");
    matrizimg.add("assets/imgchave/3.png");
    matrizimg.add("assets/imgchave/4.png");
    matrizimg.add("assets/imgchave/5.png");
    matrizimg.add("assets/imgchave/6.png");
    matrizimg.add("assets/imgchave/7.png");
    matrizimg.add("assets/imgchave/8.png");
    matrizimg.add("assets/imgchave/9.png");
    matrizimg.add("assets/imgchave/10.png");
    matrizimg.add("assets/imgchave/11.png");
    matrizimg.add("assets/imgchave/12.png");
    matrizimg.add("assets/imgchave/13.png");
    matrizimg.add("assets/imgchave/14.png");
    matrizimg.add("assets/imgchave/15.png");
    matrizimg.add("assets/imgchave/16.png");
    matrizimg.add("assets/imgchave/17.png");
    matrizimg.add("assets/imgchave/18.png");
    matrizimg.add("assets/imgchave/19.png");
    matrizimg.add("assets/imgchave/20.png");
    matrizimg.add("assets/imgchave/21.png");
    matrizimg.add("assets/imgchave/22.png");
    matrizimg.add("assets/imgchave/23.png");
    matrizimg.add("assets/imgchave/24.png");
    matrizimg.add("assets/imgchave/25.png");
    matrizimg.add("assets/imgchave/26.png");
    matrizimg.add("assets/imgchave/27.png");
    matrizimg.add("assets/imgchave/28.png");
    matrizimg.add("assets/imgchave/29.png");
    matrizimg.add("assets/imgchave/30.png");
    matrizimg.add("assets/imgchave/31.png");
    matrizimg.add("assets/imgchave/32.png");
    matrizimg.add("assets/imgchave/33.png");
    matrizimg.add("assets/imgchave/34.png");
    matrizimg.add("assets/imgchave/35.png");
    matrizimg.add("assets/imgchave/36.png");
    matrizimg.add("assets/imgchave/37.png");
    matrizimg.add("assets/imgchave/38.png");
    matrizimg.add("assets/imgchave/39.png");
    matrizimg.add("assets/imgchave/40.png");
    matrizimg.add("assets/imgchave/41.png");
    matrizimg.add("assets/imgchave/42.png");
    matrizimg.add("assets/imgchave/43.png");
    matrizimg.add("assets/imgchave/44.png");
    matrizimg.add("assets/imgchave/45.png");
    matrizimg.add("assets/imgchave/46.png");
    matrizimg.add("assets/imgchave/47.png");
    matrizimg.add("assets/imgchave/48.png");
    matrizimg.add("assets/imgchave/49.png");
    matrizimg.add("assets/imgchave/50.png");
    matrizimg.add("assets/imgchave/51.png");
    matrizimg.add("assets/imgchave/52.png");
    matrizimg.add("assets/imgchave/53.png");
    matrizimg.add("assets/imgchave/54.png");
    matrizimg.add("assets/imgchave/55.png");
    matrizimg.add("assets/imgchave/56.png");
    matrizimg.add("assets/imgchave/57.png");
    matrizimg.add("assets/imgchave/58.png");
    matrizimg.add("assets/imgchave/59.png");
    matrizimg.add("assets/imgchave/60.png");
    matrizimg.add("assets/imgchave/61.png");
    matrizimg.add("assets/imgchave/62.png");
    matrizimg.add("assets/imgchave/63.png");
    matrizimg.add("assets/imgchave/64.png");
    matrizimg.add("assets/imgchave/65.png");
    matrizimg.add("assets/imgchave/66.png");
    matrizimg.add("assets/imgchave/67.png");
    matrizimg.add("assets/imgchave/68.png");
    matrizimg.add("assets/imgchave/69.png");
    matrizimg.add("assets/imgchave/70.png");
    matrizimg.add("assets/imgchave/71.png");
    matrizimg.add("assets/imgchave/72.png");
    matrizimg.add("assets/imgchave/73.png");
    matrizimg.add("assets/imgchave/74.png");
    matrizimg.add("assets/imgchave/75.png");
    matrizimg.add("assets/imgchave/76.png");
    matrizimg.add("assets/imgchave/77.png");
    matrizimg.add("assets/imgchave/78.png");
    matrizimg.add("assets/imgchave/79.png");
    matrizimg.add("assets/imgchave/80.png");
    matrizimg.add("assets/imgchave/81.png");
    matrizimg.add("assets/imgchave/82.png");
    matrizimg.add("assets/imgchave/83.png");
    matrizimg.add("assets/imgchave/84.png");
    matrizimg.add("assets/imgchave/85.png");
    matrizimg.add("assets/imgchave/86.png");
    matrizimg.add("assets/imgchave/87.png");
    matrizimg.add("assets/imgchave/88.png");
    matrizimg.add("assets/imgchave/89.png");
    matrizimg.add("assets/imgchave/90.png");
    matrizimg.add("assets/imgchave/91.png");
    matrizimg.add("assets/imgchave/92.png");
    matrizimg.add("assets/imgchave/93.png");
    matrizimg.add("assets/imgchave/94.png");
    matrizimg.add("assets/imgchave/95.png");
    matrizimg.add("assets/imgchave/96.png");
    matrizimg.add("assets/imgchave/97.png");
    matrizimg.add("assets/imgchave/98.png");
    matrizimg.add("assets/imgchave/99.png");
    matrizimg.add("assets/imgchave/100.png");
    matrizimg.add("assets/imgchave/101.png");
    matrizimg.add("assets/imgchave/102.png");
    matrizimg.add("assets/imgchave/103.png");
    matrizimg.add("assets/imgchave/104.png");
    matrizimg.add("assets/imgchave/105.png");
    matrizimg.add("assets/imgchave/106.png");
    matrizimg.add("assets/imgchave/107.png");
    matrizimg.add("assets/imgchave/108.png");
    matrizimg.add("assets/imgchave/109.png");
    matrizimg.add("assets/imgchave/110.png");
    matrizimg.add("assets/imgchave/111.png");
    matrizimg.add("assets/imgchave/112.png");
    matrizimg.add("assets/imgchave/113.png");
    matrizimg.add("assets/imgchave/114.png");
    matrizimg.add("assets/imgchave/115.png");
    matrizimg.add("assets/imgchave/116.png");
    matrizimg.add("assets/imgchave/117.png");
    matrizimg.add("assets/imgchave/118.png");
    matrizimg.add("assets/imgchave/119.png");
    matrizimg.add("assets/imgchave/120.png");
    matrizimg.add("assets/imgchave/121.png");
    matrizimg.add("assets/imgchave/122.png");
    matrizimg.add("assets/imgchave/123.png");
    matrizimg.add("assets/imgchave/124.png");
    matrizimg.add("assets/imgchave/125.png");
    matrizimg.add("assets/imgchave/126.png");
    matrizimg.add("assets/imgchave/127.png");
    matrizimg.add("assets/imgchave/128.png");
    matrizimg.add("assets/imgchave/129.png");
    matrizimg.add("assets/imgchave/130.png");
    matrizimg.add("assets/imgchave/131.png");
    matrizimg.add("assets/imgchave/132.png");
    matrizimg.add("assets/imgchave/133.png");
    matrizimg.add("assets/imgchave/134.png");




    indiceij = matrizindice.indexOf("[$i][$j]");

    indiceik = matrizindice.indexOf("[$i][$k]");
    if (indiceij >= 0) {
      matrizij = matriztexto.elementAt(indiceij);
      imgij = matrizimg.elementAt(indiceij);
    } else {
      matrizij = null;
      imgij = "null";
    }

    if (indiceik >= 0) {
      matrizik = matriztexto.elementAt(indiceik);
      imgik = matrizimg.elementAt(indiceik);
    } else {
      matrizik = null;
      imgik = "null";
    }
  }
}
